## Warunki wilgotności i temperatury

## w pomieszczeniach magazynowych archiwum zakładowego

| Rodzaj dokumentacji                                            | Właściwa temperatura powietrza (w stopniach Celsjusza)   | Właściwa temperatura powietrza (w stopniach Celsjusza)   | Dopuszczalne wahania dobowe temperatury powietrza (w stopniach Celsjusza)   | Właściwa wilgotność względna powietrza (w % RH)   | Właściwa wilgotność względna powietrza (w % RH)   | Dopuszczalne wahania dobowe wilgotności względnej powietrza (w % RH)   |
|----------------------------------------------------------------|----------------------------------------------------------|----------------------------------------------------------|-----------------------------------------------------------------------------|---------------------------------------------------|---------------------------------------------------|------------------------------------------------------------------------|
|                                                                | min.                                                     | maks                                                     | Dopuszczalne wahania dobowe temperatury powietrza (w stopniach Celsjusza)   | min.                                              | maks                                              | Dopuszczalne wahania dobowe wilgotności względnej powietrza (w % RH)   |
| 1. Papier                                                      | 14                                                       | 18                                                       | 1                                                                           | 30                                                | 50                                                | 3                                                                      |
| 2. Dokumentacja audiowizualna:                                 |                                                          |                                                          |                                                                             |                                                   |                                                   |                                                                        |
| 2a. Fotografia czarno-biała (negatywy i pozytywy)              | 3                                                        | 18                                                       | 2                                                                           | 20                                                | 50                                                | 5                                                                      |
| 2b. Fotografia kolorowa (negatywy i pozytywy), taśma filmowa   | 3                                                        | 18                                                       | 2                                                                           | 20                                                | 50                                                | 5                                                                      |
| 2c. Taśmy magnetyczne do analogowego zapisu obrazu lub dźwięku | 8                                                        | 18                                                       | 2                                                                           | 20                                                | 50                                                | 5                                                                      |
| 3. Informatyczne nośniki danych                                | 12                                                       | 18                                                       | 2                                                                           | 30                                                | 40                                                | 5                                                                      |\n\n\n
