## B - Struktura metadanych opisujących przesyłkę wychodzącą (zestaw minimalny)

| Lp.   | Nazwa elementu                                                                                                                                                                                                                       | Sposób zapisu                                                                                                                                                                  | Wymagalność *                     | Powtarzal ność   |
|-------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------|------------------|
| 1     | Oznaczenie odpowiedzialności za treść przesyłki, w tym                                                                                                                                                                               |                                                                                                                                                                                |                                   | tak              |
| 1a    | imię i nazwisko pracownika dokonującego czynności w systemie EZD (przygotowanie projektu pisma, akceptacja pisma                                                                                                                     | tekst zapisanyw sposób umożliwiający automatyczne rozdzielenie nazwiska i imion (zaleca się automatyczne wpisywanie na podstawie zidentyfikowanego w systemie EZD użytkownika) | wymagane                          | nie              |
| 1b    | stanowisko pracownika dokonującego czynności w systemie, o których mowa w 1a                                                                                                                                                         | tekst (zaleca się automatyczne wpisywanie na podstawie zidentyfikowanego w systemie EZD użytkownika)                                                                           | wymagane                          | nie              |
| 2     | Oznaczenie adresata, w tym:                                                                                                                                                                                                          |                                                                                                                                                                                |                                   | tak              |
| 2a    | nazwa adresata niebędącego osobą fizyczną                                                                                                                                                                                            | tekst                                                                                                                                                                          | wymagane, jeżeli nie określono 2b | nie              |
| 2b    | nazwisko i imiona osoby fizycznej (odpowiedniki cech informacyjnych wymienionych w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne) | tekst zapisanyw sposób umożliwiający automatyczne rozdzielenie nazwiska i imion                                                                                                | wymagane, jeżeli nie określono 2a | nie              |
| 3     | Adres adresata, o którym mowa w pkt 1, a w tym:                                                                                                                                                                                      |                                                                                                                                                                                |                                   | nie              |

| 3a   | kod pocztowy                                                                                                                                                                                                  | tekst                                                                                  | opcjonalne   | nie   |
|------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|--------------|-------|
| 3b   | miejscowość (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne) | tekst                                                                                  | wymagane     | nie   |
| 3c   | ulica (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne)       | tekst                                                                                  | opcjonalne   | nie   |
| 3d   | budynek (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne)     | tekst                                                                                  | opcjonalne   | nie   |
| 3e   | lokal (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 z dnia 17 lutego 2005 r. ustawy o informatyzacji działalności podmiotów realizujących zadania publiczne)       | tekst                                                                                  | opcjonalne   | nie   |
| 3f   | skrytka pocztowa (nr skrytki w urzędzie pocztowym)                                                                                                                                                            | tekst                                                                                  | opcjonalne   | nie   |
| 3g   | kraj                                                                                                                                                                                                          | tekst                                                                                  | wymagane     | nie   |
| 3h   | e-mail (adres poczty elektronicznej)                                                                                                                                                                          | tekst                                                                                  | opcjonalne   | tak   |
| 4    | Data widniejąca na piśmie                                                                                                                                                                                     | data w formacie RRRR- MM-DD, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry arabskie | wymagane     | nie   |

<!-- image -->

|    |                                                                                                                                                                                                  | miesiąca, DD to dwie cyfry dnia; dopuszcza się podanie niepełnej daty, na przykład tylko RRRR albo RRRR- MM, jeżeli dokładna data nie jest znana                                                                                        |            |     |
|----|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|-----|
|  5 | Data nadania przesyłki                                                                                                                                                                           | data w formacie RRRR- MM-DD, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry arabskie miesiąca, DD to dwie cyfry dnia; dopuszcza się podanie niepełnej daty, na przykład tylko RRRR albo RRRR- MM, jeżeli dokładna data nie jest znana | opcjonalne | nie |
|  6 | Oznaczenie rodzaju dokumentu na podstawie zdefiniowanego i zatwierdzonego słownika rodzajów dokumentów (na przykład pismo, faktura, wniosek, skarga, nota księgowa, umowa, opinia, notatka itd.) | tekst                                                                                                                                                                                                                                   | opcjonalne | tak |
|  7 | Nadany automatycznie unikatowyw całym systemie EZD identyfikator dokumentu                                                                                                                       | tekst bez spacji i znaków: ( \ ) - ukośnik lewy ( / ) - ukośnik prawy ( * ) - gwiazdka ( ? ) - znak zapytania ( : ) - dwukropek ( = ) - znak równości ( , ) - przecinek ( ; ) - średnik                                                 | wymagane   | nie |

<!-- image -->

|   8 | Tytuł - zwięzłe określenie odnoszące się do treści dokumentu (na przykład sprawozdanie z przygotowań do Euro 2012, projekt instrukcji kancelaryjnej, notatka z wyjazdu do Brukseli, faktura za wywóz nieczystości)   | tekst                                                                                                                                                                                                         | wymagane                                 | nie   |
|-----|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------|-------|
|   9 | Dostęp - określenie dostępu                                                                                                                                                                                          | możliwe wartości: publiczny - dostępnyw całości, publiczny - dostępny częściowo, niepubliczny                                                                                                                 | wymagane                                 | nie   |
|  10 | Liczba załączników                                                                                                                                                                                                   | liczba naturalna                                                                                                                                                                                              | opcjonalne                               | nie   |
|  11 | Format                                                                                                                                                                                                               | tekst - nazwa formatu danych zastosowanego przy tworzeniu dokumentu                                                                                                                                           | wymagane dla dokumentów elektronicznyc h | nie   |
|  12 | Uwagi - dodatkowe informacje dotyczące rejestrowanej przesyłki                                                                                                                                                       | tekst                                                                                                                                                                                                         | opcjonalne                               | tak   |
|  13 | Typ (wg Dublin Core Metadata Initiative. Type Vocabulary) http://dublincore.org/documents/d cmi-type-vocabulary/ zgodnie z przepisami wynikającymi z art. 5 ust. 2a ustawy archiwalnej                               | możliwe wartości: Collection (nieuporządkowany zbiór danych), Dataset (uporządkowany zbiór danych), MovingImage (obraz ruchomy), PhysicalObject (obiekt fizyczny), Software (oprogramowanie), Sound (dźwięk), | wymagane                                 | nie   |

|    |                                                                                                                                                                                   | StillImage (obraz nieruchomy), Text (tekst) - oznacza tekst złożony z wyrazów przeznaczonych do czytania niezależnie od sposobu utrwalenia, w tym pismo wydrukowane na papierze, odbitkę fotograficzną tekstu, tekst zapisany zarówno w pliku rastrowym, jak i tekstowym; zaleca się wpisywanie wartości domyślnej oznaczenia typu =text   |          |     |
|----|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|-----|
| 14 | Sposób wysyłki na podstawie zdefiniowanego i zatwierdzonego słownika (na przykład list zwykły, list polecony, goniec, poczta elektroniczna, elektroniczna skrzynka podawcza itd.) | tekst                                                                                                                                                                                                                                                                                                                                      | wymagane | nie |\n
