## A - Struktura metadanych opisujących przesyłkę wpływającą (zestaw minimalny)

| Lp.   | Nazwa elementu                                                                                                                                                                                                                       | Sposób zapisu                                                                   | Wymagalność *                     | Powtarzal ność   |
|-------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|-----------------------------------|------------------|
| 1     | Oznaczenie nadawcy przesyłki, w tym:                                                                                                                                                                                                 |                                                                                 |                                   | tak              |
| 1a    | nazwa nadawcy niebędącego osobą fizyczną                                                                                                                                                                                             | tekst                                                                           | wymagane, jeżeli nie określono 1b | nie              |
| 1b    | nazwisko i imiona osoby fizycznej (odpowiedniki cech informacyjnych wymienionych w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne) | tekst zapisanyw sposób umożliwiający automatyczne rozdzielenie nazwiska i imion | wymagane, jeżeli nie określono 1a | nie              |
| 2     | Adres nadawcy, o którym mowa w pkt 1, w tym:                                                                                                                                                                                         |                                                                                 |                                   | nie              |
| 2a    | kod pocztowy                                                                                                                                                                                                                         | tekst                                                                           | opcjonalne                        | nie              |
| 2b    | miejscowość (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne)                        | tekst                                                                           | wymagane                          | nie              |

<!-- image -->

| 2c   | ulica (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne)   | tekst                                                                                                                                                                                                                                   | opcjonalne   | nie   |
|------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------|-------|
| 2d   | budynek (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne) | tekst                                                                                                                                                                                                                                   | opcjonalne   | nie   |
| 2e   | lokal (odpowiedniki cechy informacyjnej wymienionej w przepisach wydanych na podstawie art. 18 ustawy z dnia 17 lutego 2005 r. o informatyzacji działalności podmiotów realizujących zadania publiczne)   | tekst                                                                                                                                                                                                                                   | opcjonalne   | nie   |
| 2f   | skrytka pocztowa (nr skrytki w urzędzie pocztowym)                                                                                                                                                        | tekst                                                                                                                                                                                                                                   | opcjonalne   | nie   |
| 2g   | kraj                                                                                                                                                                                                      | tekst                                                                                                                                                                                                                                   | wymagane     | nie   |
| 2h   | e-mail (adres poczty elektronicznej)                                                                                                                                                                      | tekst                                                                                                                                                                                                                                   | opcjonalne   | tak   |
| 3    | Data widniejąca na piśmie                                                                                                                                                                                 | data w formacie RRRR- MM-DD, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry arabskie miesiąca, DD to dwie cyfry dnia; dopuszcza się podanie niepełnej daty, na przykład tylko RRRR albo RRRR- MM, jeżeli dokładna data nie jest znana | wymagane     | nie   |
| 4    | Data nadania przesyłki                                                                                                                                                                                    | data w formacie RRRR-                                                                                                                                                                                                                   | opcjonalne   | nie   |

<!-- image -->

|    |                                                                                                                                                                                                  | MM-DD, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry arabskie miesiąca, DD to dwie cyfry dnia; dopuszcza się podanie niepełnej daty, na przykład tylko RRRR albo RRRR- MM, jeżeli dokładna data nie jest znana                         |            |     |
|----|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|-----|
|  5 | Data wpływu przesyłki                                                                                                                                                                            | data w formacie RRRR- MM-DD, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry arabskie miesiąca, DD to dwie cyfry dnia                                                                                                                    | wymagane   | nie |
|  6 | Data i czas wykonania rejestracji dokumentu w systemie EZD (zapisywana automatycznie)                                                                                                            | Data i czas w formacie RRRR-MM- DDThh:mm:ss, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry miesiąca, DD to dwie cyfry dnia, hh to dwie cyfry godziny, mmto dwie cyfry minut, ss to dwie cyfry sekund, na przykład 1997- 07-16T19:20:30 | wymagane   | nie |
|  7 | Oznaczenie rodzaju dokumentu na podstawie zdefiniowanego i zatwierdzonego słownika rodzajów dokumentów (na przykład pismo, faktura, wniosek, skarga, nota księgowa, umowa, opinia, notatka itd.) | tekst                                                                                                                                                                                                                                     | opcjonalne | tak |
|  8 | Nadany automatycznie unikatowyw całym systemie EZD identyfikator dokumentu                                                                                                                       | tekst bez spacji i znaków: ( \ ) - ukośnik lewy ( / ) - ukośnik prawy ( * ) - gwiazdka                                                                                                                                                    | wymagane   | nie |

<!-- image -->

|    |                                                                                                                                                                                                                                                          | ( ? ) - znak zapytania ( : ) - dwukropek ( = ) - znak równości ( , ) - przecinek ( ; ) - średnik   |                                          |     |
|----|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|------------------------------------------|-----|
|  9 | Tytuł - zwięzłe określenie odnoszące się do treści dokumentu (na przykład sprawozdanie z przygotowań do Euro 2012, projekt instrukcji kancelaryjnej, notatka z wyjazdu do Brukseli, faktura za wywóz nieczystości)                                       | tekst                                                                                              | wymagane                                 | nie |
| 10 | Dostęp - określenie dostępu                                                                                                                                                                                                                              | możliwe wartości: publiczny - dostępnyw całości, publiczny - dostępny częściowo, niepubliczny      | wymagane                                 | nie |
| 11 | Liczba załączników                                                                                                                                                                                                                                       | liczba naturalna                                                                                   | opcjonalne                               | nie |
| 12 | Format                                                                                                                                                                                                                                                   | tekst - nazwa formatu danych zastosowanego przy tworzeniu dokumentu                                | wymagane dla dokumentów elektronicznyc h | nie |
| 13 | Uwagi - dodatkowe informacje dotyczące rejestrowanej przesyłki wpływającej (na przykład skan tylko 1 strona - razem ponad 500 stron, załącznik - kalendarz w formacie większym niż A3, załączona płyta CD zapisane 500 MB, załączony film na płycie DVD) | tekst                                                                                              | opcjonalne                               | tak |
| 14 | Typ (wg Dublin Core Metadata Initiative. Type Vocabulary) http://dublincore.org/documents/d                                                                                                                                                              | możliwe wartości: Collection (nieuporządkowany zbiór                                               | wymagane                                 | nie |

|    | cmi-type-vocabulary/ zgodnie z przepisami wynikającymi z art. 5 ust. 2a ustawy archiwalnej                                                                                             | danych), Dataset (uporządkowany zbiór danych), MovingImage (obraz ruchomy), PhysicalObject (obiekt fizyczny), Software (oprogramowanie), Sound (dźwięk), StillImage (obraz nieruchomy), Text (tekst) - oznacza tekst złożony z wyrazów przeznaczonych do czytania niezależnie od sposobu utrwalenia, w tym pismo wydrukowane na papierze, odbitkę fotograficzną tekstu, tekst zapisany zarówno w pliku rastrowym, jak i tekstowym; zaleca się wpisywanie wartości domyślnej oznaczenia typu =text   |                       |     |
|----|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|-----|
| 15 | Sposób dostarczenia na podstawie zdefiniowanego i zatwierdzonego słownika (na przykład list zwykły, list polecony, goniec, poczta elektroniczna, elektroniczna skrzynka podawcza itd.) | tekst                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | opcjonalne            | nie |
| 16 | Znak nadany przesyłce przez nadawcę                                                                                                                                                    | tekst                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | wymagane, jeżeli jest | nie |\n
