## C - Struktura metadanych opisujących elementy akt sprawy niebędące przesyłkami (zestaw minimalny)

| Lp.   | Nazwa elementu                                                                                                                               | Sposób zapisu                                                                                            | Wymagalność *   | Powtarzal ność   |
|-------|----------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|-----------------|------------------|
| 1     | Oznaczenie odpowiedzialności za treść                                                                                                        |                                                                                                          |                 | tak              |
| 1a    | imię i nazwisko pracownika dokonującego czynności w systemie EZD (przygotowanie projektu pisma, przygotowanie notatki, opinii, stanowiska, o | tekst zapisanyw sposób umożliwiający automatyczne rozdzielenie nazwiska i imion (zaleca się automatyczne | wymagane        | nie              |

<!-- image -->

|    | których mowa w § 7 ust. 2, akceptacją pisma)                                                                                                                  | wpisywanie na podstawie zidentyfikowanego w systemie EZD użytkownika)                                                                                                                                                                     |            |     |
|----|---------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|-----|
| 1b | stanowisko pracownika dokonującego czynności w systemie, o których mowa w 1a                                                                                  | tekst (zaleca się automatyczne wpisywanie na podstawie zidentyfikowanego w systemie EZD użytkownika)                                                                                                                                      | wymagane   | nie |
| 2  | Data i czas włączenia do akt sprawyw systemie EZD (zapisywana automatycznie)                                                                                  | data i czas w formacie RRRR-MM- DDThh:mm:ss, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry miesiąca, DD to dwie cyfry dnia, hh to dwie cyfry godziny, mmto dwie cyfry minut, ss to dwie cyfry sekund, na przykład 1997- 07-16T19:20:30 | wymagane   | nie |
| 3  | Oznaczenie rodzaju dokumentu na podstawie zdefiniowanego i zatwierdzonego słownika rodzajów dokumentów (na przykład pismo, notatka, opinia, prezentacja itd.) | tekst                                                                                                                                                                                                                                     | opcjonalne | tak |
| 4  | Nadany automatycznie unikatowyw całym systemie EZD identyfikator dokumentu                                                                                    | tekst bez spacji i znaków: ( \ ) - ukośnik lewy ( / ) - ukośnik prawy ( * ) - gwiazdka ( ? ) - znak zapytania ( : ) - dwukropek ( = ) - znak równości ( , ) - przecinek                                                                   | wymagane   | nie |

<!-- image -->

|    |                                                                                                                                                                                                                    | ( ; ) - średnik                                                                                                                                                                                                                                                           |                                          |     |
|----|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------|-----|
|  5 | Tytuł - zwięzłe określenie odnoszące się do treści dokumentu (na przykład sprawozdanie z przygotowań do Euro 2012, projekt instrukcji kancelaryjnej, notatka z wyjazdu do Brukseli, faktura za wywóz nieczystości) | tekst                                                                                                                                                                                                                                                                     | wymagane                                 | nie |
|  6 | Dostęp - określenie dostępu                                                                                                                                                                                        | możliwe wartości: publiczny - dostępnyw całości, publiczny - dostępny częściowo, niepubliczny                                                                                                                                                                             | wymagane                                 | nie |
|  7 | Format                                                                                                                                                                                                             | tekst - nazwa formatu danych zastosowanego przy tworzeniu dokumentu                                                                                                                                                                                                       | wymagane dla dokumentów elektronicznyc h | nie |
|  8 | Typ (wg Dublin Core Metadata Initiative. Type Vocabulary) http://dublincore.org/documents/d cmi-type-vocabulary/ zgodnie z przepisami wynikającymi z art. 5 ust. 2a ustawy archiwalnej                             | możliwe wartości: Collection (nieuporządkowany zbiór danych), Dataset (uporządkowany zbiór danych), MovingImage (obraz ruchomy), PhysicalObject (obiekt fizyczny), Software (oprogramowanie), Sound (dźwięk), StillImage (obraz nieruchomy), Text (tekst) - oznacza tekst | wymagane                                 | nie |

| złożony ze słów przeznaczonych do czytania niezależnie od sposobu utrwalenia, w tym pismo wydrukowane na papierze, odbitkę fotograficzną tekstu, tekst zapisany zarówno w pliku rastrowym, jak i tekstowym; zaleca się wpisywanie wartości domyślnej oznaczenia typu =text   |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n
