## D - Struktura metadanych opisujących sprawę (zestaw minimalny)

| Lp.   | Nazwa elementu                                  | Sposób zapisu                                                                                                                                                       | Wymagalność*                      | Powtarzal ność   |
|-------|-------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------|------------------|
| 1     | Oznaczenie odpowiedzialności za treść           |                                                                                                                                                                     |                                   | tak              |
| 1a    | imię i nazwisko pracownika zakładającego sprawę | tekst zapisanyw sposób umożliwiający automatyczne rozdzielenie nazwiska i imion (automatyczne wpisywanie na podstawie zidentyfikowanego w systemie EZD użytkownika) | wymagane, jeżeli nie określono 1b | nie              |
| 1b    | imię i nazwisko pracownika prowadzącego sprawę  | tekst zapisanyw sposób umożliwiający automatyczne rozdzielenie nazwiska i imion (automatyczne wpisywanie na podstawie zidentyfikowanego w                           | wymagane, jeżeli nie określono 1a | tak              |

<!-- image -->

|    |                                                                                                                                                                                               | systemie EZD użytkownika)                                                                                                                                                                                                                 |                                                                                                                                               |     |
|----|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|-----|
|  2 | Data i czas założenia sprawy w systemie EZD (zapisywana automatycznie)                                                                                                                        | data i czas w formacie RRRR-MM- DDThh:mm:ss, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry miesiąca, DD to dwie cyfry dnia, hh to dwie cyfry godziny, mmto dwie cyfry minut, ss to dwie cyfry sekund, na przykład 1997- 07-16T19:20:30 | wymagane                                                                                                                                      | nie |
|  3 | Data i czas ostatniego elementu akt sprawy (zapisywana automatycznie najpóźniejsza z dat spośród dat wymienionych w częściach A, B lub C załącznika)                                          | data i czas w formacie RRRR-MM-DD, gdzie RRRR to cztery cyfry roku, MMto dwie cyfry miesiąca, DD to dwie cyfry dnia, na przykład 1997-07- 16                                                                                              | wymagane w momencie eksportu danych do paczki archiwalnej, o której mowa w przepisach wydanych na podstawie art. 5 ust. 2c ustawy archiwalnej | nie |
|  4 | Znak sprawy (zapisywany automatycznie po wybraniu właściwej pozycji wykazu akt)                                                                                                               | zgodnie z zasadami określonymi w instrukcji kancelaryjnej                                                                                                                                                                                 | wymagane                                                                                                                                      | nie |
|  5 | Tytuł - zwięzłe określenie odnoszące się do treści sprawy (na przykład przygotowanie projektu instrukcji kancelaryjnej, wyjazd do Brukseli na ..., przygotowanie umowy na wywóz nieczystości) | tekst                                                                                                                                                                                                                                     | wymagane                                                                                                                                      | nie |
|  6 | Dostęp - określenie dostępu (automatyczne przyporządkowanie odpowiedniej wartości na                                                                                                          | możliwe wartości: publiczny - dostępnyw całości, publiczny -                                                                                                                                                                              | wymagane w momencie eksportu danych do paczki                                                                                                 | nie |

|    | podstawie metadanych dokumentów elektronicznych znajdujących się w aktach sprawy)                                                                                                      | dostępny częściowo, niepubliczny                             | archiwalnej, o której mowa w przepisach wydanych na podstawie art. 5 ust. 2c ustawy archiwalnej                                               |     |
|----|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|-----|
|  7 | Format                                                                                                                                                                                 | ustalona wartość "Multipart/Header-Set"                      | wymagane w momencie eksportu danych do paczki archiwalnej, o której mowa w przepisach wydanych na podstawie art. 5 ust. 2c ustawy archiwalnej | nie |
|  8 | Typ (wg Dublin Core Metadata Initiative. Type Vocabulary) http://dublincore.org/document s/dcmi-type-vocabulary/ zgodnie z przepisami wynikającymi z art. 5 ust. 2a ustawy archiwalnej | ustalona wartość: Collection (nieuporządkowany zbiór danych) | wymagane w momencie eksportu danych do paczki archiwalnej, o której mowa w przepisach wydanych na podstawie art. 5 ust. 2c ustawy archiwalnej | nie |
|  9 | Opis                                                                                                                                                                                   | Tekst                                                        | opcjonalny                                                                                                                                    | Nie |

* Wymagalność elementu metadanych oznacza obowiązek jego określenia, jeżeli to określenie jest możliwe.\n
